# Generated by Django 2.0.6 on 2018-06-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsusers',
            options={},
        ),
    ]
